=== sebastianp21/PCbuilder/schemas/CaseFan.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Case Fan Schema",
  "description": "Schema for case fan components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "size": {
      "type": [
        "number",
        "null"
      ],
      "description": "The fan size in mm (e.g., 120)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "quantity": {
      "type": [
        "number",
        "null"
      ],
      "description": "Number of fans included in the package (e.g., 3). Important for multi-packs"
    },
    "min_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "max_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "min_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "max_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "pwm": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the fan supports Pulse Width Modulation for speed control"
    },
    "led": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of LED lighting, if any (e.g., 'Addressable RGB', 'RGB', 'None')"
    },
    "connector": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of connector(s) the fan uses (e.g., '4-pin PWM + 3-pin 5V Addressable RGB')"
    },
    "controller": {
      "type": [
        "string",
        "null"
      ],
      "description": "If the fan includes a controller, specify the type (e.g., '5V Addressable RGB'). Otherwise, indicate 'None'"
    },
    "static_pressure": {
      "type": [
        "number",
        "null"
      ],
      "description": "The static pressure of the fan in mmHâ‚‚O"
    },
    "flow_direction": {
      "type": [
        "string",
        "null"
      ],
      "description": "The direction of the airflow (e.g., 'Standard', 'Reverse')"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/c1caf142-e09d-4f53-b1a4-8b45f3e96c01.json
{
  "opendb_id": "c1caf142-e09d-4f53-b1a4-8b45f3e96c01",
  "metadata": {
    "name": "Rosewill RNBL-131209R 120mm Black Red LED 59.8 CFM",
    "manufacturer": "Rosewill",
    "part_numbers": [],
    "series": "RNBL-131209R",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 59.8,
  "max_airflow": null,
  "min_noise_level": 36,
  "max_noise_level": null,
  "pwm": false,
  "led": "Red",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/5e271ab9-0160-47e6-abb6-b523cd345d53.json
{
  "opendb_id": "5e271ab9-0160-47e6-abb6-b523cd345d53",
  "metadata": {
    "name": "Iceberg Thermal IceGALE 140mm Gray PWM 2-Pack",
    "manufacturer": "Iceberg Thermal",
    "part_numbers": [],
    "series": "IceGALE",
    "variant": "140mm Gray"
  },
  "size": 140,
  "color": [
    "GREY"
  ],
  "quantity": 2,
  "min_airflow": 96,
  "max_airflow": null,
  "min_noise_level": 0,
  "max_noise_level": 36,
  "pwm": true,
  "led": "None",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 2.65,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B08NWJCFR5",
    "newegg_sku": "1YF-0184-00029"
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/202ec9c6-34a0-414b-8ddb-0156a4d1192e.json
{
  "opendb_id": "202ec9c6-34a0-414b-8ddb-0156a4d1192e",
  "metadata": {
    "name": "Deepcool FK120 120mm Black PWM 68.99 CFM",
    "manufacturer": "Deepcool",
    "part_numbers": [],
    "series": "FK120",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 68.99,
  "max_airflow": null,
  "min_noise_level": 28,
  "max_noise_level": null,
  "pwm": true,
  "led": "None",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 2.19,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/662a7733-62f0-412b-b9dd-09df6d2db664.json
{
  "opendb_id": "662a7733-62f0-412b-b9dd-09df6d2db664",
  "metadata": {
    "name": "be quiet! Silent Wings 2 140mm Black PWM 60.4 CFM",
    "manufacturer": "be quiet!",
    "part_numbers": [],
    "series": "Silent",
    "variant": "140mm Black"
  },
  "size": 140,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 60.4,
  "max_airflow": null,
  "min_noise_level": 16.4,
  "max_noise_level": null,
  "pwm": true,
  "led": "None",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 0.81,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/2e5eedb8-ad15-4224-9928-5a73d63b3d69.json
{
  "opendb_id": "2e5eedb8-ad15-4224-9928-5a73d63b3d69",
  "metadata": {
    "name": "Alpenföhn JetStream 120mm Black PWM 55.326 CFM",
    "manufacturer": "Alpenföhn",
    "part_numbers": [],
    "series": "JetStream",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 55.326,
  "max_airflow": null,
  "min_noise_level": 22.8,
  "max_noise_level": null,
  "pwm": true,
  "led": "None",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 1.74,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/23d6bbbc-9579-4b22-8120-fe41f89fe9a3.json
{
  "opendb_id": "23d6bbbc-9579-4b22-8120-fe41f89fe9a3",
  "metadata": {
    "name": "Akasa Vegas TLY 140mm Black / White 41.2 CFM Addressable RGB",
    "manufacturer": "Akasa",
    "part_numbers": [],
    "series": "Vegas",
    "variant": "140mm Black / White"
  },
  "size": 140,
  "color": [
    "BLACK",
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": 41.2,
  "max_airflow": null,
  "min_noise_level": 21.2,
  "max_noise_level": null,
  "pwm": false,
  "led": "Addressable RGB",
  "connector": "3-pin + 3-pin 5V Addressable RGB",
  "controller": "None",
  "static_pressure": 1.24,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/125d7114-1642-436f-88ab-365f9fe46a8f.json
{
  "opendb_id": "125d7114-1642-436f-88ab-365f9fe46a8f",
  "metadata": {
    "name": "BitFenix Spectre 120mm Black Red LED",
    "manufacturer": "BitFenix",
    "part_numbers": [],
    "series": "Spectre",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 43.5,
  "max_airflow": null,
  "min_noise_level": 20,
  "max_noise_level": null,
  "pwm": false,
  "led": "Red",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/644a3d65-1eb3-44b4-9649-6ad141f44c7d.json
{
  "opendb_id": "644a3d65-1eb3-44b4-9649-6ad141f44c7d",
  "metadata": {
    "name": "BitFenix Spectre 120mm Black 43.5 CFM Green LED 1-Pack",
    "manufacturer": "BitFenix",
    "part_numbers": [],
    "series": "Spectre",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 43.5,
  "max_airflow": null,
  "min_noise_level": 20,
  "max_noise_level": null,
  "pwm": false,
  "led": "Green",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": 0.62,
  "flow_direction": "Standard",
  "general_product_information": {}
}
