=== sebastianp21/PCbuilder/schemas/CaseFan.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Case Fan Schema",
  "description": "Schema for case fan components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "size": {
      "type": [
        "number",
        "null"
      ],
      "description": "The fan size in mm (e.g., 120)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "quantity": {
      "type": [
        "number",
        "null"
      ],
      "description": "Number of fans included in the package (e.g., 3). Important for multi-packs"
    },
    "min_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "max_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "min_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "max_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "pwm": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the fan supports Pulse Width Modulation for speed control"
    },
    "led": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of LED lighting, if any (e.g., 'Addressable RGB', 'RGB', 'None')"
    },
    "connector": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of connector(s) the fan uses (e.g., '4-pin PWM + 3-pin 5V Addressable RGB')"
    },
    "controller": {
      "type": [
        "string",
        "null"
      ],
      "description": "If the fan includes a controller, specify the type (e.g., '5V Addressable RGB'). Otherwise, indicate 'None'"
    },
    "static_pressure": {
      "type": [
        "number",
        "null"
      ],
      "description": "The static pressure of the fan in mmHâ‚‚O"
    },
    "flow_direction": {
      "type": [
        "string",
        "null"
      ],
      "description": "The direction of the airflow (e.g., 'Standard', 'Reverse')"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/eba5fb0b-6a70-4a56-9ddc-a4690978ad96.json
{
  "opendb_id": "eba5fb0b-6a70-4a56-9ddc-a4690978ad96",
  "metadata": {
    "name": "Zalman F1 80mm Black / Clear 1-Pack",
    "manufacturer": "Zalman",
    "part_numbers": [],
    "series": "F1",
    "variant": "80mm Black / Clear"
  },
  "size": 80,
  "color": [
    "BLACK",
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": null,
  "max_airflow": null,
  "min_noise_level": 18,
  "max_noise_level": 23,
  "pwm": false,
  "led": "None",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/5b0f124a-7f9a-4f29-b5ed-d4b77eac52d8.json
{
  "opendb_id": "5b0f124a-7f9a-4f29-b5ed-d4b77eac52d8",
  "metadata": {
    "name": "ARCTIC P PST 140mm White PWM Addressable RGB 68.9 CFM",
    "manufacturer": "ARCTIC",
    "part_numbers": [],
    "series": "P",
    "variant": "140mm White"
  },
  "size": 140,
  "color": [
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": 68.9,
  "max_airflow": null,
  "min_noise_level": 22.5,
  "max_noise_level": null,
  "pwm": true,
  "led": "Addressable RGB",
  "connector": "4-pin PWM + 3-pin 5V Addressable RGB",
  "controller": "None",
  "static_pressure": 2,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B09VDQ1L6C",
    "walmart_sku": 5085817423
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/c010ec58-9633-45e3-b455-477f00f55011.json
{
  "opendb_id": "c010ec58-9633-45e3-b455-477f00f55011",
  "metadata": {
    "name": "Iceberg Thermal IceGALE 120mm Teal / White ARGB PWM 94 CFM 1-Pack",
    "manufacturer": "Iceberg Thermal",
    "part_numbers": [],
    "series": "IceGALE",
    "variant": "120mm Teal / White"
  },
  "size": 120,
  "color": [
    "WHITE",
    "BLUE"
  ],
  "quantity": 1,
  "min_airflow": 94,
  "max_airflow": null,
  "min_noise_level": 0,
  "max_noise_level": 38,
  "pwm": true,
  "led": "Addressable RGB",
  "connector": "Proprietary PWM + 3-pin 5V Addressable RGB",
  "controller": "None",
  "static_pressure": 3.27,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B08P2DVD1X"
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/0594c1d8-6f08-4e4c-a22b-d5a65f081687.json
{
  "opendb_id": "0594c1d8-6f08-4e4c-a22b-d5a65f081687",
  "metadata": {
    "name": "Thermaltake Riing 140mm Black / White White LED 51.15 CFM 1-Pack",
    "manufacturer": "Thermaltake",
    "part_numbers": [],
    "series": "Riing",
    "variant": "140mm Black / White"
  },
  "size": 140,
  "color": [
    "BLACK",
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": 51.15,
  "max_airflow": null,
  "min_noise_level": 22.1,
  "max_noise_level": 28.1,
  "pwm": false,
  "led": "White",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": 1.58,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B00WB9MMFE",
    "walmart_sku": 46480970
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/b5fc5210-19c4-4013-bfbb-7e92ba3bd2af.json
{
  "opendb_id": "b5fc5210-19c4-4013-bfbb-7e92ba3bd2af",
  "metadata": {
    "name": "Corsair iCUE QL140 140mm Black PWM RGB 50.2 CFM 2-Pack",
    "manufacturer": "Corsair",
    "part_numbers": [],
    "series": "iCUE",
    "variant": "140mm Black"
  },
  "size": 140,
  "color": [
    "BLACK"
  ],
  "quantity": 2,
  "min_airflow": 50.2,
  "max_airflow": null,
  "min_noise_level": 26,
  "max_noise_level": null,
  "pwm": true,
  "led": "RGB",
  "connector": "4-pin PWM + Proprietary RGB",
  "controller": "Manual",
  "static_pressure": 1.4,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B07Z9SSKKP",
    "walmart_sku": 227685288
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/dd081a39-15bd-41f8-beb2-2667b0242218.json
{
  "opendb_id": "dd081a39-15bd-41f8-beb2-2667b0242218",
  "metadata": {
    "name": "Xigmatek Crystal 120mm Clear Green LED",
    "manufacturer": "Xigmatek",
    "part_numbers": [],
    "series": "Crystal",
    "variant": "120mm Clear"
  },
  "size": 120,
  "color": [
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": 68.33,
  "max_airflow": null,
  "min_noise_level": 20,
  "max_noise_level": null,
  "pwm": false,
  "led": "Green",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/1789570b-cd05-45f1-bec7-ff13a9d9c46f.json
{
  "opendb_id": "1789570b-cd05-45f1-bec7-ff13a9d9c46f",
  "metadata": {
    "name": "ARCTIC P PST 140mm Black / Transparent PWM RGB 3-Pack",
    "manufacturer": "ARCTIC",
    "part_numbers": [],
    "series": "P",
    "variant": "140mm Black / Transparent"
  },
  "size": 140,
  "color": [
    "BLACK",
    "RGB"
  ],
  "quantity": 3,
  "min_airflow": 68.9,
  "max_airflow": null,
  "min_noise_level": 0,
  "max_noise_level": 68.9,
  "pwm": true,
  "led": "RGB",
  "connector": "4-pin PWM + 4-pin 12V RGB",
  "controller": "None",
  "static_pressure": 2,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/8334464b-1e6c-4fb2-ac30-b493ca211dc3.json
{
  "opendb_id": "8334464b-1e6c-4fb2-ac30-b493ca211dc3",
  "metadata": {
    "name": "StarTech FAN12025PWM 120mm Black 78.41 CFM",
    "manufacturer": "StarTech",
    "part_numbers": [],
    "series": "FAN12025PWM",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 33.2,
  "max_airflow": 78.41,
  "min_noise_level": 17.2,
  "max_noise_level": 39,
  "pwm": false,
  "led": "None",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B006G66RAE",
    "newegg_sku": "N82E16835230044",
    "walmart_sku": 29951816
  }
}
