=== sebastianp21/PCbuilder/schemas/CaseFan.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Case Fan Schema",
  "description": "Schema for case fan components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "size": {
      "type": [
        "number",
        "null"
      ],
      "description": "The fan size in mm (e.g., 120)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "quantity": {
      "type": [
        "number",
        "null"
      ],
      "description": "Number of fans included in the package (e.g., 3). Important for multi-packs"
    },
    "min_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "max_airflow": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum airflow of the fan in CFM. If it is a constant, just fill in min_airflow and ignore max_airflow"
    },
    "min_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The minimum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "max_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The maximum noise level of the fan in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "pwm": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the fan supports Pulse Width Modulation for speed control"
    },
    "led": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of LED lighting, if any (e.g., 'Addressable RGB', 'RGB', 'None')"
    },
    "connector": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of connector(s) the fan uses (e.g., '4-pin PWM + 3-pin 5V Addressable RGB')"
    },
    "controller": {
      "type": [
        "string",
        "null"
      ],
      "description": "If the fan includes a controller, specify the type (e.g., '5V Addressable RGB'). Otherwise, indicate 'None'"
    },
    "static_pressure": {
      "type": [
        "number",
        "null"
      ],
      "description": "The static pressure of the fan in mmHâ‚‚O"
    },
    "flow_direction": {
      "type": [
        "string",
        "null"
      ],
      "description": "The direction of the airflow (e.g., 'Standard', 'Reverse')"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/407999e4-7ccb-4bf4-8b26-93a77af9c8cc.json
{
  "opendb_id": "407999e4-7ccb-4bf4-8b26-93a77af9c8cc",
  "metadata": {
    "name": "Thermalright TL-S12R 120mm Black PWM 47.6 CFM 1-Pack",
    "manufacturer": "Thermalright",
    "part_numbers": [],
    "series": "TL-S12R",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": 47.6,
  "max_airflow": null,
  "min_noise_level": 23.2,
  "max_noise_level": null,
  "pwm": true,
  "led": "None",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 1.31,
  "flow_direction": "Reverse",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/8be9b6cd-5dc7-4617-9197-01b42ca9a481.json
{
  "opendb_id": "8be9b6cd-5dc7-4617-9197-01b42ca9a481",
  "metadata": {
    "name": "Thermaltake CT120 EX Reverse 120mm Blue ARGB PWM 3-Pack",
    "manufacturer": "Thermaltake",
    "part_numbers": [],
    "series": "CT120",
    "variant": "120mm Blue"
  },
  "size": 120,
  "color": [
    "BLUE"
  ],
  "quantity": 3,
  "min_airflow": 65.82,
  "max_airflow": null,
  "min_noise_level": 31.2,
  "max_noise_level": null,
  "pwm": true,
  "led": "Addressable RGB",
  "connector": "4-pin PWM + 3-pin 5V Addressable RGB",
  "controller": "None",
  "static_pressure": 1.87,
  "flow_direction": "Reverse",
  "general_product_information": {
    "amazon_sku": "B0D7NL3BWC",
    "newegg_sku": "1YF-001G-004C4",
    "walmart_sku": 7356917062
  }
}

=== sebastianp21/PCbuilder/open-db/CaseFan/9afe3ea2-0c25-4389-abde-8593510ad39f.json
{
  "opendb_id": "9afe3ea2-0c25-4389-abde-8593510ad39f",
  "metadata": {
    "name": "LEPA LP70D12R 120mm Black",
    "manufacturer": "LEPA",
    "part_numbers": [],
    "series": "LP70D12R",
    "variant": "120mm Black"
  },
  "size": 120,
  "color": [
    "BLACK"
  ],
  "quantity": 1,
  "min_airflow": null,
  "max_airflow": null,
  "min_noise_level": 24,
  "max_noise_level": null,
  "pwm": false,
  "led": "None",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/fc7952e2-eafc-4572-b2ef-0e7568c506e5.json
{
  "opendb_id": "fc7952e2-eafc-4572-b2ef-0e7568c506e5",
  "metadata": {
    "name": "Deepcool FT14 140mm White PWM 1-Pack",
    "manufacturer": "Deepcool",
    "part_numbers": [],
    "series": "FT14",
    "variant": "140mm White"
  },
  "size": 140,
  "color": [
    "WHITE"
  ],
  "quantity": 1,
  "min_airflow": 78.83,
  "max_airflow": null,
  "min_noise_level": 25.1,
  "max_noise_level": null,
  "pwm": true,
  "led": "White",
  "connector": "4-pin PWM",
  "controller": "None",
  "static_pressure": 3.6,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/d741f7db-4103-47b5-892e-1a8493310b89.json
{
  "opendb_id": "d741f7db-4103-47b5-892e-1a8493310b89",
  "metadata": {
    "name": "Apevia AF512L-BL 120mm Blue Blue LED 5-Pack",
    "manufacturer": "Apevia",
    "part_numbers": [],
    "series": "AF512L-BL",
    "variant": "120mm Blue"
  },
  "size": 120,
  "color": [
    "BLUE"
  ],
  "quantity": 5,
  "min_airflow": 57.67,
  "max_airflow": null,
  "min_noise_level": 24.7,
  "max_noise_level": null,
  "pwm": false,
  "led": "Blue",
  "connector": "3-pin",
  "controller": "None",
  "static_pressure": null,
  "flow_direction": "Standard",
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CaseFan/b184d357-b0af-4e38-b295-0b4344ed331a.json
{
  "opendb_id": "b184d357-b0af-4e38-b295-0b4344ed331a",
  "metadata": {
    "name": "Thermaltake SWAFAN EX12 120mm Blue / White Addressable RGB PWM 57.11 CFM 3-Pack",
    "manufacturer": "Thermaltake",
    "part_numbers": [],
    "series": "SWAFAN",
    "variant": "120mm Blue / White"
  },
  "size": 120,
  "color": [
    "BLUE",
    "WHITE"
  ],
  "quantity": 3,
  "min_airflow": 56.26,
  "max_airflow": 57.11,
  "min_noise_level": 30.6,
  "max_noise_level": 32.5,
  "pwm": true,
  "led": "Addressable RGB",
  "connector": "4-pin PWM + 3-pin 5V Addressable RGB",
  "controller": "None",
  "static_pressure": 2.39,
  "flow_direction": "Standard",
  "general_product_information": {
    "amazon_sku": "B0CTGMV3TP",
    "newegg_sku": "13C-001H-00267",
    "walmart_sku": 5445870553
  }
}
