=== sebastianp21/PCbuilder/schemas/CPUCooler.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "CPU Cooler Schema",
  "description": "Schema for CPU cooler components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "min_fan_rpm": {
      "type": [
        "number",
        "null"
      ],
      "description": "Min value of the fan's rotational speed in RPM. If it is a constant, just fill in min_fan_rpm and ignore max_fan_rpm"
    },
    "max_fan_rpm": {
      "type": [
        "number",
        "null"
      ],
      "description": "Max value of the fan's rotational speed in RPM. If it is a constant, just fill in min_fan_rpm and ignore max_fan_rpm"
    },
    "min_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The min noise level of the cooler in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "max_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The max noise level of the cooler in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "height": {
      "type": [
        "number",
        "null"
      ],
      "description": "The height of the CPU cooler in mm"
    },
    "cpu_sockets": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "An array of CPU socket types supported by the cooler (e.g., AM4, AM5, LGA 1700, LGA 1200)"
    },
    "water_cooled": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Indicates if the cooler is water-cooled"
    },
    "radiator_size": {
      "type": [
        "number",
        "null"
      ],
      "description": "If water-cooled, specify the radiator size in mm (e.g. 360, 280, 240, etc)"
    },
    "fanless": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the cooler can operate fanless"
    },
    "fan_size": {
      "type": [
        "number",
        "null"
      ],
      "description": "Size of the included fan(s) in mm (e.g. 140, 120)"
    },
    "fan_quantity": {
      "type": [
        "number",
        "null"
      ],
      "description": "Number of included fans"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/763ae303-ad6d-43d3-8793-1ca11886f6b3.json
{
  "opendb_id": "763ae303-ad6d-43d3-8793-1ca11886f6b3",
  "metadata": {
    "name": "ID-COOLING DASHFLOW BASIC Water 360mm 82.5 CFM Black",
    "manufacturer": "ID-COOLING",
    "part_numbers": [
      "DASHFLOW 360 BASIC BLACK"
    ],
    "series": "DASHFLOW",
    "variant": "Black",
    "releaseYear": null
  },
  "min_fan_rpm": 700,
  "max_fan_rpm": 1800,
  "min_noise_level": 15.2,
  "max_noise_level": 35.2,
  "color": [
    "BLACK"
  ],
  "height": null,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/89c947e7-726e-4555-924e-ad26e446d96e.json
{
  "opendb_id": "89c947e7-726e-4555-924e-ad26e446d96e",
  "metadata": {
    "name": "Scythe BIG Shuriken 2 Rev. B 45.47 CFM Sleeve Bearing Air 58mm",
    "manufacturer": "Scythe",
    "part_numbers": [
      "SCBSK-2100"
    ],
    "series": "BIG",
    "variant": "",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2000,
  "min_noise_level": 9.32,
  "max_noise_level": 33.67,
  "color": [],
  "height": 58,
  "cpu_sockets": [
    "AM2",
    "AM2",
    "AM3",
    "AM3",
    "FM1",
    "FM2",
    "FM2",
    "LGA775",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1366",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/f7279b2c-59d3-48a6-847a-10c94643dfef.json
{
  "opendb_id": "f7279b2c-59d3-48a6-847a-10c94643dfef",
  "metadata": {
    "name": "MSI MEG CORELIQUID S280 Water 280mm Black",
    "manufacturer": "MSI",
    "part_numbers": [
      "MEG CoreLiquid S280                                                    9S6-6A0431-001                                                    CLS280"
    ],
    "series": "MEG",
    "variant": "Black",
    "releaseYear": null
  },
  "min_fan_rpm": null,
  "max_fan_rpm": null,
  "min_noise_level": 24.9,
  "max_noise_level": null,
  "color": [
    "BLACK"
  ],
  "height": null,
  "cpu_sockets": [
    "AM2",
    "AM2",
    "AM3",
    "AM3",
    "AM4",
    "AM5",
    "FM1",
    "FM2",
    "FM2",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 280,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B09CQCX4VM",
    "newegg_sku": "N82E16835846028",
    "walmart_sku": 961306141
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/b5698f15-3da1-4ed1-86b8-0e4cd7abd148.json
{
  "opendb_id": "b5698f15-3da1-4ed1-86b8-0e4cd7abd148",
  "metadata": {
    "name": "NZXT Kraken X73 Water 360mm 73.11 CFM Black",
    "manufacturer": "NZXT",
    "part_numbers": [
      "RL-KRX73-01"
    ],
    "series": "Kraken",
    "variant": "Black",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2000,
  "min_noise_level": 21,
  "max_noise_level": 36,
  "color": [
    "BLACK"
  ],
  "height": null,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "sTR4",
    "sTRX4",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1366",
    "LGA1700",
    "LGA1851",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B082DYKB1F",
    "newegg_sku": "9SIAWKTJSV6878",
    "bestbuy_sku": 6408511,
    "walmart_sku": 436594045
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/93c679ad-ceb6-4d92-b381-3a638396a8cd.json
{
  "opendb_id": "93c679ad-ceb6-4d92-b381-3a638396a8cd",
  "metadata": {
    "name": "ID-COOLING SE-903-XT Air 45.8 CFM",
    "manufacturer": "ID-COOLING",
    "part_numbers": [
      "SE-903-XT"
    ],
    "series": "SE-903-XT",
    "variant": "",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2200,
  "min_noise_level": 14,
  "max_noise_level": 25.8,
  "color": [],
  "height": 123,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/dd0d6342-6268-468a-a172-4ee15e6a8683.json
{
  "opendb_id": "dd0d6342-6268-468a-a172-4ee15e6a8683",
  "metadata": {
    "name": "Thermalright Frozen Magic Scenic V2 Water 280mm 110.4 CFM White",
    "manufacturer": "Thermalright",
    "part_numbers": [
      "Frozen Magic 280 Scenic V2"
    ],
    "series": "Frozen",
    "variant": "White",
    "releaseYear": null
  },
  "min_fan_rpm": 2000,
  "max_fan_rpm": null,
  "min_noise_level": 31.4,
  "max_noise_level": null,
  "color": [
    "WHITE"
  ],
  "height": null,
  "cpu_sockets": [
    "AM2",
    "AM2",
    "AM3",
    "AM3",
    "AM4",
    "AM5",
    "FM1",
    "FM2",
    "FM2",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 280,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B0BBLY7KQH"
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/87766b61-5dfb-4367-8279-e1be080dbf11.json
{
  "opendb_id": "87766b61-5dfb-4367-8279-e1be080dbf11",
  "metadata": {
    "name": "ID-COOLING PINKFLOW Water 360mm 55.2 CFM Pink",
    "manufacturer": "ID-COOLING",
    "part_numbers": [
      "PINKFLOW 360"
    ],
    "series": "PINKFLOW",
    "variant": "Pink",
    "releaseYear": null
  },
  "min_fan_rpm": 900,
  "max_fan_rpm": 2000,
  "min_noise_level": 16.3,
  "max_noise_level": 33.5,
  "color": [
    "PINK"
  ],
  "height": null,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851",
    "LGA2011",
    "LGA2011",
    "3",
    "LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/8ef1437e-07de-4e6e-bdf6-189422ec42df.json
{
  "opendb_id": "8ef1437e-07de-4e6e-bdf6-189422ec42df",
  "metadata": {
    "name": "MasterLiquid ML120L V2 RGB",
    "manufacturer": "Cooler Master",
    "part_number": "MLW-D12M-A18PC-R2",
    "series": "MasterLiquid Lite",
    "variant": "RGB",
    "releaseYear": 2020,
    "part_numbers": []
  },
  "min_fan_rpm": 650,
  "max_fan_rpm": 1800,
  "min_noise_level": null,
  "max_noise_level": 10,
  "height": null,
  "cpu_sockets": [
    "Intel® LGA 1851",
    "Intel® LGA 1700",
    "Intel® LGA 1200",
    "Intel® LGA 2066",
    "Intel® LGA 2011-v3",
    "Intel® LGA 2011",
    "Intel® LGA 1151",
    "Intel® LGA 1150",
    "Intel® LGA 1155",
    "Intel® LGA 1156",
    "AMD® AM5",
    "AMD® AM4"
  ],
  "water_cooled": true,
  "radiator_size": 120,
  "fanless": false,
  "fan_size": 120,
  "fan_quantity": 1,
  "color": [],
  "general_product_information": {
    "amazon_sku": "B075XLX31G",
    "newegg_sku": "13C-000X-003C1",
    "walmart_sku": 906446322
  }
}
