=== sebastianp21/PCbuilder/schemas/CPUCooler.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "CPU Cooler Schema",
  "description": "Schema for CPU cooler components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "min_fan_rpm": {
      "type": [
        "number",
        "null"
      ],
      "description": "Min value of the fan's rotational speed in RPM. If it is a constant, just fill in min_fan_rpm and ignore max_fan_rpm"
    },
    "max_fan_rpm": {
      "type": [
        "number",
        "null"
      ],
      "description": "Max value of the fan's rotational speed in RPM. If it is a constant, just fill in min_fan_rpm and ignore max_fan_rpm"
    },
    "min_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The min noise level of the cooler in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "max_noise_level": {
      "type": [
        "number",
        "null"
      ],
      "description": "The max noise level of the cooler in dB. If it is a constant, just fill in min_noise_level and ignore max_noise_level"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "height": {
      "type": [
        "number",
        "null"
      ],
      "description": "The height of the CPU cooler in mm"
    },
    "cpu_sockets": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "An array of CPU socket types supported by the cooler (e.g., AM4, AM5, LGA 1700, LGA 1200)"
    },
    "water_cooled": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Indicates if the cooler is water-cooled"
    },
    "radiator_size": {
      "type": [
        "number",
        "null"
      ],
      "description": "If water-cooled, specify the radiator size in mm (e.g. 360, 280, 240, etc)"
    },
    "fanless": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the cooler can operate fanless"
    },
    "fan_size": {
      "type": [
        "number",
        "null"
      ],
      "description": "Size of the included fan(s) in mm (e.g. 140, 120)"
    },
    "fan_quantity": {
      "type": [
        "number",
        "null"
      ],
      "description": "Number of included fans"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/ed5d68c1-023d-4eef-9b2e-76329fd483f6.json
{
  "opendb_id": "ed5d68c1-023d-4eef-9b2e-76329fd483f6",
  "metadata": {
    "name": "Asus ROG STRIX LC III ARGB Water 360mm ARGB 70.38 CFM White",
    "manufacturer": "Asus",
    "part_numbers": [
      "ROG Strix LC III 360 ARGB WHT"
    ],
    "series": "ROG",
    "variant": "White",
    "releaseYear": null
  },
  "min_fan_rpm": 800,
  "max_fan_rpm": 2200,
  "min_noise_level": 36,
  "max_noise_level": null,
  "color": [
    "WHITE"
  ],
  "height": null,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B0CXLTXTTX",
    "newegg_sku": "N82E16835101106",
    "walmart_sku": 5389834702
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/175c2034-adef-4a41-a5c7-0092e12d6194.json
{
  "opendb_id": "175c2034-adef-4a41-a5c7-0092e12d6194",
  "metadata": {
    "name": "Deepcool LE720 Water 360mm Black",
    "manufacturer": "Deepcool",
    "part_numbers": [
      "R-LE720-BKAMMN-G-1"
    ],
    "series": "LE720",
    "variant": "Black",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2250,
  "min_noise_level": 32.9,
  "max_noise_level": null,
  "color": [
    "BLACK"
  ],
  "height": 52,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/9e8996cd-e0c8-409c-9ec9-c60f08980b32.json
{
  "opendb_id": "9e8996cd-e0c8-409c-9ec9-c60f08980b32",
  "metadata": {
    "name": "Enermax AQUAFUSION ADV Water 240mm 79.8 CFM Black",
    "manufacturer": "Enermax",
    "part_numbers": [
      "ELC-AQFA240-SQA"
    ],
    "series": "AQUAFUSION",
    "variant": "Black",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2000,
  "min_noise_level": 15,
  "max_noise_level": 32.6,
  "color": [
    "BLACK"
  ],
  "height": 54,
  "cpu_sockets": [
    "AM2AM2",
    "AM3AM3",
    "AM4AM5FM1FM2FM2",
    "LGA1150LGA1151LGA1155LGA1156LGA1200LGA1366LGA1700LGA2011LGA2011",
    "3LGA2066"
  ],
  "water_cooled": true,
  "radiator_size": 240,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B0BJ111V2Y",
    "newegg_sku": "9SIAFH7K5C5038",
    "walmart_sku": 1779448245
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/dde60b57-af03-465a-a08c-817810337c34.json
{
  "opendb_id": "dde60b57-af03-465a-a08c-817810337c34",
  "metadata": {
    "name": "Iceberg Thermal IceFLOE T65 Air 38mm Silver / Teal",
    "manufacturer": "Iceberg Thermal",
    "part_numbers": [
      "ICEFLOE65-00A"
    ],
    "series": "IceFLOE",
    "variant": "Silver / Teal",
    "releaseYear": null
  },
  "min_fan_rpm": 1000,
  "max_fan_rpm": 3000,
  "min_noise_level": 31.5,
  "max_noise_level": null,
  "color": [
    "GREY",
    "BLUE"
  ],
  "height": 38,
  "cpu_sockets": [
    "AM2",
    "AM2",
    "AM3",
    "AM3",
    "AM4",
    "AM5",
    "FM1",
    "FM2",
    "FM2",
    "LGA775",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1366"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/add3bdae-860c-44ae-8109-40a93265ecd7.json
{
  "opendb_id": "add3bdae-860c-44ae-8109-40a93265ecd7",
  "metadata": {
    "name": "Jonsbo CR-1000 Air 158mm 66.81 CFM White",
    "manufacturer": "Jonsbo",
    "part_numbers": [
      "CR-1000 White"
    ],
    "series": "CR-1000",
    "variant": "White",
    "releaseYear": null
  },
  "min_fan_rpm": 700,
  "max_fan_rpm": 1800,
  "min_noise_level": 20.55,
  "max_noise_level": 37.2,
  "color": [
    "WHITE"
  ],
  "height": 158,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/2fab0617-343c-4754-a321-f04b366d42d9.json
{
  "opendb_id": "2fab0617-343c-4754-a321-f04b366d42d9",
  "metadata": {
    "name": "MSI MAG CORELIQUID 360R V2 Water 360mm White",
    "manufacturer": "MSI",
    "part_numbers": [
      "MAG CORELIQUID 360R V2 WHITE306-7ZW1B53-813"
    ],
    "series": "MAG",
    "variant": "White",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 2000,
  "min_noise_level": 14.3,
  "max_noise_level": 34.3,
  "color": [
    "WHITE"
  ],
  "height": null,
  "cpu_sockets": [
    "AM2AM2",
    "AM3AM3",
    "AM4AM5sTR4sTRX4FM1FM2FM2",
    "LGA1150LGA1151LGA1155LGA1156LGA1200LGA1366LGA1700"
  ],
  "water_cooled": true,
  "radiator_size": 360,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B0B45MDFXH"
  }
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/010abcce-a3d8-488c-a89d-9713092820c1.json
{
  "opendb_id": "010abcce-a3d8-488c-a89d-9713092820c1",
  "metadata": {
    "name": "Deepcool AK400 Air 155mm Black / Silver",
    "manufacturer": "Deepcool",
    "part_numbers": [
      "R-AK400-BKNNMN-G-1"
    ],
    "series": "AK400",
    "variant": "Black / Silver",
    "releaseYear": null
  },
  "min_fan_rpm": 500,
  "max_fan_rpm": 1850,
  "min_noise_level": 29,
  "max_noise_level": null,
  "color": [
    "BLACK",
    "GREY"
  ],
  "height": 155,
  "cpu_sockets": [
    "AM4",
    "AM5",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200",
    "LGA1700",
    "LGA1851"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/CPUCooler/faf70b02-c080-4305-92f4-715defbbe3fc.json
{
  "opendb_id": "faf70b02-c080-4305-92f4-715defbbe3fc",
  "metadata": {
    "name": "Cooler Master MasterAIR G200P Air 39mm Black / Silver",
    "manufacturer": "Cooler Master",
    "part_numbers": [
      "MAP-G2PN-126PC-R1"
    ],
    "series": "MasterAIR",
    "variant": "Black / Silver",
    "releaseYear": null
  },
  "min_fan_rpm": 800,
  "max_fan_rpm": 2000,
  "min_noise_level": 6,
  "max_noise_level": 28,
  "color": [
    "BLACK",
    "GREY"
  ],
  "height": 39,
  "cpu_sockets": [
    "AM2",
    "AM2",
    "AM3",
    "AM3",
    "AM4",
    "FM1",
    "FM2",
    "FM2",
    "LGA1150",
    "LGA1151",
    "LGA1155",
    "LGA1156",
    "LGA1200"
  ],
  "water_cooled": false,
  "radiator_size": null,
  "fanless": false,
  "fan_size": null,
  "fan_quantity": null,
  "general_product_information": {
    "amazon_sku": "B082WZDY8B",
    "walmart_sku": 654429577
  }
}
