=== sebastianp21/PCbuilder/schemas/PSU.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Power Supply Schema",
  "description": "Schema for power supply components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "wattage": {
      "type": [
        "number",
        "null"
      ],
      "description": "The total power output of the PSU in watts (e.g., 1000)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the PSU (e.g., ATX)"
    },
    "efficiency_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The 80 PLUS efficiency certification level (e.g., 80 PLUS Gold)"
    },
    "cybernetics_efficiency_rating": {
      "type": [
        "number",
        "null"
      ],
      "description": "The Cybernetics efficiency rating of the PSU (e.g., Cybenetics Titanium, Cybenetics Platinum, Cybenetics Gold)"
    },
    "cybernetics_noise_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The Cybernetics noise rating of the PSU (e.g., Cybernetics A++. Cybernetics A+, Cybernetics Standard, etc)"
    },
    "modular": {
      "type": [
        "string",
        "null"
      ],
      "description": "The modularity of the PSU cables (e.g., Full, Semi-Modular, Non-Modular)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "length": {
      "type": [
        "number",
        "null"
      ],
      "description": "The length of the PSU in mm (e.g., 140)"
    },
    "fanless": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the PSU operates without a fan"
    },
    "connectors": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "atx_24_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of ATX 24-pin (20+4) connectors (main motherboard power)"
        },
        "eps_8_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of EPS12V 8-pin (4+4) connectors (CPU power)"
        },
        "pcie_12vhpwr": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 5.0 12VHPWR (12+4) pin connectors (for high-end GPUs). Also referred to as 16-pin (12+4)"
        },
        "pcie_6_plus_2_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 6+2-pin connectors (commonly used for GPUs)"
        },
        "sata": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of SATA power connectors"
        },
        "molex_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Molex 4-pin peripheral connectors (for older devices)"
        },
        "floppy_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Floppy 4-pin connectors. Increasingly rare"
        }
      }
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/e9e5b95c-9344-4769-92ac-c837aebfda02.json
{
  "opendb_id": "e9e5b95c-9344-4769-92ac-c837aebfda02",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 4,
    "sata": 6,
    "molex_4_pin": 6,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Zalman zm-650-XG ATX 650W Semi-Modular 80+ Gold Certified",
    "manufacturer": "Zalman",
    "part_numbers": [
      "zm-650-XG"
    ],
    "series": "zm-650-XG",
    "variant": "650W Gold"
  },
  "wattage": 650,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Semi-Modular",
  "color": [],
  "length": 180,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/0c297025-d0a0-4991-ab6f-8c6222670c76.json
{
  "opendb_id": "0c297025-d0a0-4991-ab6f-8c6222670c76",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 2,
    "sata": 5,
    "molex_4_pin": 4,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Thermaltake Litepower 600W Non-Modular",
    "manufacturer": "Thermaltake",
    "part_numbers": [
      "W0355RA"
    ],
    "series": "Litepower",
    "variant": "600W "
  },
  "wattage": 600,
  "form_factor": "ATX",
  "efficiency_rating": "",
  "modular": "Non-Modular",
  "color": [],
  "length": 140,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/bc202566-a16c-4786-8125-6b96315f2de0.json
{
  "opendb_id": "bc202566-a16c-4786-8125-6b96315f2de0",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 8,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Segotep GM Black 850W Fully Modular 80+ Gold Certified",
    "manufacturer": "Segotep",
    "part_numbers": [
      "CP-PSU-ST-GM850"
    ],
    "series": "GM",
    "variant": "850W Gold"
  },
  "wattage": 850,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 140,
  "fanless": false,
  "general_product_information": {
    "amazon_sku": "B08F1NFSG4",
    "newegg_sku": "9SIBGX1JA26863",
    "walmart_sku": 304094942
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/5b3a25ef-e702-4ebd-93ff-4c5df9789abe.json
{
  "opendb_id": "5b3a25ef-e702-4ebd-93ff-4c5df9789abe",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 8,
    "molex_4_pin": 8,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Thermaltake TR2 1000W Semi-Modular 80+",
    "manufacturer": "Thermaltake",
    "part_numbers": [
      "TRX-1000M"
    ],
    "series": "TR2",
    "variant": "1000W 80+"
  },
  "wattage": 1000,
  "form_factor": "ATX",
  "efficiency_rating": "80+",
  "modular": "Semi-Modular",
  "color": [],
  "length": 180,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/ca3b849b-5bae-47fc-a080-fafa84c2351f.json
{
  "opendb_id": "ca3b849b-5bae-47fc-a080-fafa84c2351f",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 2,
    "molex_4_pin": 4,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "FSP Group ATX400-PNT ATX 400W Non-Modular",
    "manufacturer": "FSP Group",
    "part_numbers": [
      "ATX400-PNT"
    ],
    "series": "ATX400-PNT",
    "variant": "400W "
  },
  "wattage": 400,
  "form_factor": "ATX",
  "efficiency_rating": "",
  "modular": "Non-Modular",
  "color": [],
  "length": null,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/e9dcb7d1-2188-496c-a838-0826d219b5ca.json
{
  "opendb_id": "e9dcb7d1-2188-496c-a838-0826d219b5ca",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 4,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "ENDORFY Supremo FM6 Black 1000W Fully Modular 80+ Gold Certified ATX",
    "manufacturer": "ENDORFY",
    "part_numbers": [
      "EY7A011-U1                                            EY7A011"
    ],
    "series": "Supremo",
    "variant": "1000W Gold"
  },
  "wattage": 1000,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 140,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/f5a276d7-8b35-42c1-aa70-9e2bd863868b.json
{
  "opendb_id": "f5a276d7-8b35-42c1-aa70-9e2bd863868b",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 8,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Silverstone Triton 1000Rz Black 1000W Fully Modular",
    "manufacturer": "Silverstone",
    "part_numbers": [
      "SST-TR1000R-GM"
    ],
    "series": "Triton",
    "variant": "1000W "
  },
  "wattage": 1000,
  "form_factor": "ATX",
  "efficiency_rating": "",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 140,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/f413ab9f-a039-405b-94e6-910ec4bf650a.json
{
  "opendb_id": "f413ab9f-a039-405b-94e6-910ec4bf650a",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 2,
    "sata": 5,
    "molex_4_pin": 4,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "LEPA B550-MB 550W Semi-Modular 80+ Bronze Certified",
    "manufacturer": "LEPA",
    "part_numbers": [
      "B550-MB"
    ],
    "series": "B550-MB",
    "variant": "550W Bronze"
  },
  "wattage": 550,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Bronze",
  "modular": "Semi-Modular",
  "color": [],
  "length": 160,
  "fanless": false,
  "general_product_information": {}
}
