=== sebastianp21/PCbuilder/schemas/PSU.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Power Supply Schema",
  "description": "Schema for power supply components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "wattage": {
      "type": [
        "number",
        "null"
      ],
      "description": "The total power output of the PSU in watts (e.g., 1000)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the PSU (e.g., ATX)"
    },
    "efficiency_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The 80 PLUS efficiency certification level (e.g., 80 PLUS Gold)"
    },
    "cybernetics_efficiency_rating": {
      "type": [
        "number",
        "null"
      ],
      "description": "The Cybernetics efficiency rating of the PSU (e.g., Cybenetics Titanium, Cybenetics Platinum, Cybenetics Gold)"
    },
    "cybernetics_noise_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The Cybernetics noise rating of the PSU (e.g., Cybernetics A++. Cybernetics A+, Cybernetics Standard, etc)"
    },
    "modular": {
      "type": [
        "string",
        "null"
      ],
      "description": "The modularity of the PSU cables (e.g., Full, Semi-Modular, Non-Modular)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "length": {
      "type": [
        "number",
        "null"
      ],
      "description": "The length of the PSU in mm (e.g., 140)"
    },
    "fanless": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the PSU operates without a fan"
    },
    "connectors": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "atx_24_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of ATX 24-pin (20+4) connectors (main motherboard power)"
        },
        "eps_8_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of EPS12V 8-pin (4+4) connectors (CPU power)"
        },
        "pcie_12vhpwr": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 5.0 12VHPWR (12+4) pin connectors (for high-end GPUs). Also referred to as 16-pin (12+4)"
        },
        "pcie_6_plus_2_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 6+2-pin connectors (commonly used for GPUs)"
        },
        "sata": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of SATA power connectors"
        },
        "molex_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Molex 4-pin peripheral connectors (for older devices)"
        },
        "floppy_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Floppy 4-pin connectors. Increasingly rare"
        }
      }
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/45213438-9ebc-4b14-beea-e999008ebc5c.json
{
  "opendb_id": "45213438-9ebc-4b14-beea-e999008ebc5c",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 4,
    "sata": 10,
    "molex_4_pin": 8,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "G.Skill PS750G ATX 750W Fully Modular 80+ Gold Certified",
    "manufacturer": "G.Skill",
    "part_numbers": [
      "GP-GD750A-CWV1"
    ],
    "series": "PS750G",
    "variant": "750W Gold"
  },
  "wattage": 750,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 180,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/1dd17bac-4eef-4a6b-8b4c-a0b08cb6550c.json
{
  "opendb_id": "1dd17bac-4eef-4a6b-8b4c-a0b08cb6550c",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 2,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 4,
    "sata": 10,
    "molex_4_pin": 5,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "SeaSonic Platinum 760W Fully Modular 80+ Platinum",
    "manufacturer": "SeaSonic",
    "part_numbers": [
      "SS-760XP2"
    ],
    "series": "Platinum",
    "variant": "760W Platinum"
  },
  "wattage": 760,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Platinum",
  "modular": "Full",
  "color": [],
  "length": 160,
  "fanless": false,
  "general_product_information": {}
}
