=== sebastianp21/PCbuilder/schemas/PSU.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Power Supply Schema",
  "description": "Schema for power supply components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "wattage": {
      "type": [
        "number",
        "null"
      ],
      "description": "The total power output of the PSU in watts (e.g., 1000)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the PSU (e.g., ATX)"
    },
    "efficiency_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The 80 PLUS efficiency certification level (e.g., 80 PLUS Gold)"
    },
    "cybernetics_efficiency_rating": {
      "type": [
        "number",
        "null"
      ],
      "description": "The Cybernetics efficiency rating of the PSU (e.g., Cybenetics Titanium, Cybenetics Platinum, Cybenetics Gold)"
    },
    "cybernetics_noise_rating": {
      "type": [
        "string",
        "null"
      ],
      "description": "The Cybernetics noise rating of the PSU (e.g., Cybernetics A++. Cybernetics A+, Cybernetics Standard, etc)"
    },
    "modular": {
      "type": [
        "string",
        "null"
      ],
      "description": "The modularity of the PSU cables (e.g., Full, Semi-Modular, Non-Modular)"
    },
    "color": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "The color of this product (e.g., ['Black', 'Red']). Each color of the product should be included in the array."
    },
    "length": {
      "type": [
        "number",
        "null"
      ],
      "description": "The length of the PSU in mm (e.g., 140)"
    },
    "fanless": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the PSU operates without a fan"
    },
    "connectors": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "atx_24_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of ATX 24-pin (20+4) connectors (main motherboard power)"
        },
        "eps_8_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of EPS12V 8-pin (4+4) connectors (CPU power)"
        },
        "pcie_12vhpwr": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 5.0 12VHPWR (12+4) pin connectors (for high-end GPUs). Also referred to as 16-pin (12+4)"
        },
        "pcie_6_plus_2_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of PCIe 6+2-pin connectors (commonly used for GPUs)"
        },
        "sata": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of SATA power connectors"
        },
        "molex_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Molex 4-pin peripheral connectors (for older devices)"
        },
        "floppy_4_pin": {
          "type": [
            "number",
            "null"
          ],
          "description": "The number of Floppy 4-pin connectors. Increasingly rare"
        }
      }
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/36038b34-c97e-4805-8ab6-4a6698fec036.json
{
  "opendb_id": "36038b34-c97e-4805-8ab6-4a6698fec036",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 6,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Thermaltake Toughpower GT Beige 750W Fully Modular 80+ Gold",
    "manufacturer": "Thermaltake",
    "part_numbers": [
      "PS-TPT-0750FNFAGE-3"
    ],
    "series": "Toughpower",
    "variant": "750W Gold"
  },
  "wattage": 750,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "BROWN"
  ],
  "length": 140,
  "fanless": false,
  "general_product_information": {
    "amazon_sku": "B0D85QDP2Y"
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/adc13455-e455-4f67-943b-4a55dcb26891.json
{
  "opendb_id": "adc13455-e455-4f67-943b-4a55dcb26891",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 1,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 6,
    "molex_4_pin": 3,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Silverstone Strider ATX 400W Non-Modular 80+ Bronze Certified",
    "manufacturer": "Silverstone",
    "part_numbers": [
      "ST40F-ESB"
    ],
    "series": "Strider",
    "variant": "400W Bronze"
  },
  "wattage": 400,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Bronze",
  "modular": "Non-Modular",
  "color": [],
  "length": 140,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/a8e3d0d9-fcf9-4e81-83c1-ea8e747cfac6.json
{
  "opendb_id": "a8e3d0d9-fcf9-4e81-83c1-ea8e747cfac6",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 2,
    "pcie_12vhpwr": 1,
    "pcie_6_plus_2_pin": 2,
    "sata": 8,
    "molex_4_pin": 3,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Silverstone Extreme 850R Black SFX 850W Fully Modular 80+ Platinum",
    "manufacturer": "Silverstone",
    "part_numbers": [
      "SST-EX850R-PM"
    ],
    "series": "Extreme",
    "variant": "850W "
  },
  "wattage": 850,
  "form_factor": "SFX",
  "efficiency_rating": "",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 100,
  "fanless": false,
  "general_product_information": {
    "amazon_sku": "B0BQCV927S",
    "newegg_sku": "2AM-006F-001E1",
    "walmart_sku": 2875759223
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/7645443f-55bf-42c8-9979-86388473434f.json
{
  "opendb_id": "7645443f-55bf-42c8-9979-86388473434f",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 2,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 4,
    "sata": 8,
    "molex_4_pin": 5,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Super Flower Golden Green HX 650W Non-Modular 80+ Gold",
    "manufacturer": "Super Flower",
    "part_numbers": [
      "SF-650P14XE (HX)"
    ],
    "series": "Golden",
    "variant": "650W Gold"
  },
  "wattage": 650,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Non-Modular",
  "color": [],
  "length": 145,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/8a610fb0-f4ba-419e-a2c9-573ae196d48d.json
{
  "opendb_id": "8a610fb0-f4ba-419e-a2c9-573ae196d48d",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 2,
    "pcie_12vhpwr": 1,
    "pcie_6_plus_2_pin": 3,
    "sata": 8,
    "molex_4_pin": 2,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Deepcool PN650M White 650W Fully Modular 80+ Gold Certified ATX",
    "manufacturer": "Deepcool",
    "part_numbers": [
      "R-PN650M-FC0W-US                                                    R-PN650M-FC0W-UK                                                    PN650M WH                                                    R-PN650M-FC0W-EU                                                    R-PN650M-FC0W-WO"
    ],
    "series": "PN650M",
    "variant": "650W Gold"
  },
  "wattage": 650,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "WHITE"
  ],
  "length": 140,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/ee5ec974-358f-42c6-a320-b4d452e17f90.json
{
  "opendb_id": "ee5ec974-358f-42c6-a320-b4d452e17f90",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 9,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "ASRock Steel Legend SL-850G Black 850W Fully Modular 80+ Gold Certified",
    "manufacturer": "ASRock",
    "part_numbers": [
      "SL-850G"
    ],
    "series": "Steel",
    "variant": "850W Gold"
  },
  "wattage": 850,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [
    "BLACK"
  ],
  "length": 150,
  "fanless": false,
  "general_product_information": {
    "newegg_sku": "N82E16817955009"
  }
}

=== sebastianp21/PCbuilder/open-db/PSU/5f8b09ad-c4e9-4700-a07f-a623831811d0.json
{
  "opendb_id": "5f8b09ad-c4e9-4700-a07f-a623831811d0",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 0,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 0,
    "sata": 8,
    "molex_4_pin": 0,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Corsair RM750 ATX 750W Fully Modular 80+ Gold Certified",
    "manufacturer": "Corsair",
    "part_numbers": [
      "RM750                                                    CP-9020055-UK                                                    CP-9020055-WW                                                    CP-9020055-NA                                                    CP-9020055-EU"
    ],
    "series": "RM750",
    "variant": "750W Gold"
  },
  "wattage": 750,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Full",
  "color": [],
  "length": 180,
  "fanless": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/PSU/8061f19f-2dbd-43fc-a9e3-1df0358e12b4.json
{
  "opendb_id": "8061f19f-2dbd-43fc-a9e3-1df0358e12b4",
  "connectors": {
    "atx_24_pin": 1,
    "eps_8_pin": 2,
    "pcie_12vhpwr": 0,
    "pcie_6_plus_2_pin": 10,
    "sata": 16,
    "molex_4_pin": 8,
    "floppy_4_pin": 0
  },
  "metadata": {
    "name": "Thermaltake Toughpower 1500W Semi-Modular 80+ Gold Certified",
    "manufacturer": "Thermaltake",
    "part_numbers": [
      "PS-TPD-1500MPCGUS-1"
    ],
    "series": "Toughpower",
    "variant": "1500W Gold"
  },
  "wattage": 1500,
  "form_factor": "ATX",
  "efficiency_rating": "80+ Gold",
  "modular": "Semi-Modular",
  "color": [],
  "length": 220,
  "fanless": false,
  "general_product_information": {}
}
