=== sebastianp21/PCbuilder/schemas/Storage.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Storage Schema",
  "description": "Schema for storage components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "capacity": {
      "type": [
        "number",
        "null"
      ],
      "description": "The storage capacity of the drive in GB (e.g., 4000 GB)"
    },
    "type": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of storage drive (either HDD or SSD)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the drive (e.g., M.2-2280, 2.5\", 3.5\")"
    },
    "interface": {
      "type": [
        "string",
        "null"
      ],
      "description": "The interface used by the drive (e.g., M.2 PCIe 4.0 X4, SATA 6Gb/s)"
    },
    "cache": {
      "type": [
        "number",
        "null"
      ],
      "description": "The cache size of the drive in MB"
    },
    "nvme": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the drive uses the NVMe protocol. Only applicable to SSDs"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/98655c26-a166-4612-9b4e-70860819c04c.json
{
  "opendb_id": "98655c26-a166-4612-9b4e-70860819c04c",
  "metadata": {
    "name": "Crucial BX300 240GB SSD 2.5\" SATA 6.0 Gb/s",
    "manufacturer": "Crucial",
    "part_numbers": [
      "CT240BX300SSD1"
    ],
    "series": "BX300",
    "variant": "240GB"
  },
  "capacity": 240,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B0742BC3DQ"
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/7a352299-eae0-410d-94f6-393cc48dcee6.json
{
  "opendb_id": "7a352299-eae0-410d-94f6-393cc48dcee6",
  "metadata": {
    "name": "TEAMGROUP T-Force GE PRO Graphene 1TB SSD M.2-2280 PCIe 5.0 X4 NVMe",
    "manufacturer": "TEAMGROUP",
    "part_numbers": [
      "TM8FFS001T0C129"
    ],
    "series": "T-Force",
    "variant": "1000GB"
  },
  "capacity": 1000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 5.0 X4",
  "nvme": true,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/1026404e-7a6b-468e-bb41-7804d64cb139.json
{
  "opendb_id": "1026404e-7a6b-468e-bb41-7804d64cb139",
  "metadata": {
    "name": "Patriot Burst 960GB SSD 2.5\" SATA 6.0 Gb/s",
    "manufacturer": "Patriot",
    "part_numbers": [
      "PBU960GS25SSDR"
    ],
    "series": "Burst",
    "variant": "960GB"
  },
  "capacity": 960,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/72761649-b085-411d-9604-949d1fedc98f.json
{
  "opendb_id": "72761649-b085-411d-9604-949d1fedc98f",
  "metadata": {
    "name": "TEAMGROUP T-Force Delta Max RGB 250GB SSD 2.5\" SATA 6.0 Gb/s",
    "manufacturer": "TEAMGROUP",
    "part_numbers": [
      "T253TM250G3C302"
    ],
    "series": "T-Force",
    "variant": "250GB"
  },
  "capacity": 250,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/2111163d-e51e-4332-9db5-f204feaf4912.json
{
  "opendb_id": "2111163d-e51e-4332-9db5-f204feaf4912",
  "metadata": {
    "name": "Intel D3-S4610 7.68 TB SSD 2.5\" SATA 6.0 Gb/s",
    "manufacturer": "Intel",
    "part_numbers": [
      "SSDSC2KG076T801"
    ],
    "series": "D3-S4610",
    "variant": "7000GB"
  },
  "capacity": 7000,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B082J3N7B4",
    "newegg_sku": "9SIA12KJHZ2506",
    "walmart_sku": 277985938
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/dce8f985-5bde-428c-9638-306967ab457e.json
{
  "opendb_id": "dce8f985-5bde-428c-9638-306967ab457e",
  "metadata": {
    "name": "ADATA LEGEND 700 GOLD 2TB SSD M.2-2280 PCIe 3.0 X4 NVMe",
    "manufacturer": "ADATA",
    "part_numbers": [
      "SLEG-700G-2TCS-S48"
    ],
    "series": "LEGEND",
    "variant": "2000GB"
  },
  "capacity": 2000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B0CD65JQYC",
    "walmart_sku": 3949399692
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/70642c0b-7bf7-463b-a928-29de85105e9a.json
{
  "opendb_id": "70642c0b-7bf7-463b-a928-29de85105e9a",
  "metadata": {
    "name": "Kingston KC600 256GB SSD 2.5\" SATA 6.0 Gb/s",
    "manufacturer": "Kingston",
    "part_numbers": [
      "SKC600MS256G"
    ],
    "series": "KC600",
    "variant": "256GB"
  },
  "capacity": 256,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B08ZNSNL1K",
    "newegg_sku": "0D9-001B-004P2",
    "walmart_sku": 888902658
  }
}
