=== sebastianp21/PCbuilder/schemas/Storage.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Storage Schema",
  "description": "Schema for storage components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "capacity": {
      "type": [
        "number",
        "null"
      ],
      "description": "The storage capacity of the drive in GB (e.g., 4000 GB)"
    },
    "type": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of storage drive (either HDD or SSD)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the drive (e.g., M.2-2280, 2.5\", 3.5\")"
    },
    "interface": {
      "type": [
        "string",
        "null"
      ],
      "description": "The interface used by the drive (e.g., M.2 PCIe 4.0 X4, SATA 6Gb/s)"
    },
    "cache": {
      "type": [
        "number",
        "null"
      ],
      "description": "The cache size of the drive in MB"
    },
    "nvme": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the drive uses the NVMe protocol. Only applicable to SSDs"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/620d620d-8221-4828-9f6e-713e58f365ec.json
{
  "opendb_id": "620d620d-8221-4828-9f6e-713e58f365ec",
  "metadata": {
    "name": "Samsung 840 120GB SSD 2.5\" SATA",
    "manufacturer": "Samsung",
    "part_numbers": [
      "MZ-7TD120KW"
    ],
    "series": "840",
    "variant": "120GB"
  },
  "capacity": 120,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/fed28fce-dc6e-4725-9b3b-6efbdd4fe826.json
{
  "opendb_id": "fed28fce-dc6e-4725-9b3b-6efbdd4fe826",
  "metadata": {
    "name": "Kingston A2000 1TB SSD M.2-2280 PCIe 3.0 X4 NVMe",
    "manufacturer": "Kingston",
    "part_numbers": [
      "SA2000M8",
      "1000G"
    ],
    "series": "A2000",
    "variant": "1000GB"
  },
  "capacity": 1000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B07VXC9QMH",
    "newegg_sku": "9SIA22FKCT1714",
    "walmart_sku": 785106647
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/8e45272c-d4c6-4e87-bd11-d2452b2d24b7.json
{
  "opendb_id": "8e45272c-d4c6-4e87-bd11-d2452b2d24b7",
  "metadata": {
    "name": "Western Digital Purple 8TB 3.5\" HDD 7200RPM SATA",
    "manufacturer": "Western Digital",
    "part_numbers": [
      "WD82PURZ"
    ],
    "series": "Purple",
    "variant": "8000GB"
  },
  "capacity": 8000,
  "type": "7200 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B07RRCQVN1",
    "walmart_sku": 915258149
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/303b4349-4ffb-4030-9dfb-03f9a69b00ea.json
{
  "opendb_id": "303b4349-4ffb-4030-9dfb-03f9a69b00ea",
  "metadata": {
    "name": "Lexar NM610 500GB M.2-2280 SSD PCIe 3.0 x4 NVMe",
    "manufacturer": "Lexar",
    "part_numbers": [
      "LNM610-500RBNA                                                    LNM610-500RB"
    ],
    "series": "NM610",
    "variant": "500GB"
  },
  "capacity": 500,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B07WL653V8",
    "walmart_sku": 350332505
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/5b034752-4036-4b04-af25-0471b70b57fe.json
{
  "opendb_id": "5b034752-4036-4b04-af25-0471b70b57fe",
  "metadata": {
    "name": "Oyen Digital Dash Pro 4TB SSD M.2 PCIe 4.0 NVMe w/Heat Sink",
    "manufacturer": "Oyen Digital",
    "part_numbers": [
      "PS5-4T-2280"
    ],
    "series": "Dash",
    "variant": "4000GB"
  },
  "capacity": 4000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 4.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B09RYSXQDG",
    "walmart_sku": 985248867
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/db3deedc-8868-4314-87e2-98931a5d8818.json
{
  "opendb_id": "db3deedc-8868-4314-87e2-98931a5d8818",
  "metadata": {
    "name": "Inland QN322 500GB SSD M.2-2280 PCIe 3.0 X4 NVME",
    "manufacturer": "Inland",
    "part_numbers": [
      "500GB QN322 NVM"
    ],
    "series": "QN322",
    "variant": "500GB"
  },
  "capacity": 500,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B0B96SP5RZ"
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/4a452e84-c30b-4b05-94c4-d2d65bd2bc9c.json
{
  "opendb_id": "4a452e84-c30b-4b05-94c4-d2d65bd2bc9c",
  "metadata": {
    "name": "SK hynix Gold S31 500GB,Internal,2.5 inch (SHGS31500GS) Solid State Drive",
    "manufacturer": "SK hynix",
    "part_number": "SHGS31500GS",
    "series": "Gold S31",
    "variant": null,
    "releaseYear": 2019,
    "part_numbers": []
  },
  "capacity": 500,
  "type": "SSD",
  "form_factor": "2.5\"",
  "interface": "SATA III",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B07SK5BNM1",
    "bestbuy_sku": 6431941,
    "walmart_sku": 364084167
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/3ad83203-83af-4924-8f2d-c988d7b2fa7b.json
{
  "opendb_id": "3ad83203-83af-4924-8f2d-c988d7b2fa7b",
  "metadata": {
    "name": "Western Digital WD_BLACK SN850P for PS5 2TB SSD M.2-2280 PCIe 4.0 NVMe",
    "manufacturer": "Western Digital",
    "part_numbers": [
      "WDBBYV0020BNC-WRSN"
    ],
    "series": "WD_BLACK",
    "variant": "2000GB"
  },
  "capacity": 2000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 4.0 X4",
  "nvme": true,
  "general_product_information": {
    "amazon_sku": "B0C47ZX1WB",
    "newegg_sku": "N82E16820250258",
    "bestbuy_sku": 6541326,
    "walmart_sku": 1967745437
  }
}
