=== sebastianp21/PCbuilder/schemas/Storage.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": [
    "object",
    "null"
  ],
  "title": "Storage Schema",
  "description": "Schema for storage components",
  "required": [
    "metadata"
  ],
  "properties": {
    "opendb_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Unique identifier for the document (UUID v4)"
    },
    "capacity": {
      "type": [
        "number",
        "null"
      ],
      "description": "The storage capacity of the drive in GB (e.g., 4000 GB)"
    },
    "type": {
      "type": [
        "string",
        "null"
      ],
      "description": "The type of storage drive (either HDD or SSD)"
    },
    "form_factor": {
      "type": [
        "string",
        "null"
      ],
      "description": "The physical size and shape of the drive (e.g., M.2-2280, 2.5\", 3.5\")"
    },
    "interface": {
      "type": [
        "string",
        "null"
      ],
      "description": "The interface used by the drive (e.g., M.2 PCIe 4.0 X4, SATA 6Gb/s)"
    },
    "cache": {
      "type": [
        "number",
        "null"
      ],
      "description": "The cache size of the drive in MB"
    },
    "nvme": {
      "type": [
        "boolean",
        "null"
      ],
      "description": "Whether the drive uses the NVMe protocol. Only applicable to SSDs"
    },
    "metadata": {
      "type": [
        "object",
        "null"
      ],
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Full product name"
        },
        "manufacturer": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product manufacturer"
        },
        "part_numbers": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "description": "Array of manufacturer's part numbers/SKUs"
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "description": "Product series name"
        },
        "variant": {
          "type": [
            "string",
            "null"
          ],
          "description": "Specific variant in the series"
        },
        "releaseYear": {
          "type": [
            "number",
            "null"
          ],
          "description": "Year of release"
        }
      }
    },
    "general_product_information": {
      "type": [
        "object",
        "null"
      ],
      "description": "General product information and retailer SKUs",
      "properties": {
        "amazon_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Amazon product SKU"
        },
        "newegg_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Newegg product SKU"
        },
        "bestbuy_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Best Buy product SKU"
        },
        "walmart_sku": {
          "type": [
            "number",
            "null"
          ],
          "description": "Walmart product SKU"
        },
        "adorama_sku": {
          "type": [
            "string",
            "null"
          ],
          "description": "Adorama product SKU"
        },
        "manufacturer_url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Official manufacturer product URL"
        }
      }
    }
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/e226656d-74f6-43f6-addb-af20f5bc36ff.json
{
  "opendb_id": "e226656d-74f6-43f6-addb-af20f5bc36ff",
  "metadata": {
    "name": "Seagate FireCuda 520 Rev 2.0 1TB SSD M.2-2280 PCIe 4.0 X4 NVMe",
    "manufacturer": "Seagate",
    "part_numbers": [
      "ZP1000GV3A012"
    ],
    "series": "FireCuda",
    "variant": "1000GB"
  },
  "capacity": 1000,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 4.0 X4",
  "nvme": true,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/7bf784a5-7496-4f81-8688-3635379a49aa.json
{
  "opendb_id": "7bf784a5-7496-4f81-8688-3635379a49aa",
  "metadata": {
    "name": "Mushkin Pilot-E 500GB SSD M.2-2280 NVMe",
    "manufacturer": "Mushkin",
    "part_numbers": [
      "MKNSSDPE500GB-D8"
    ],
    "series": "Pilot-E",
    "variant": "500GB"
  },
  "capacity": 500,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/dd1d5777-5e9a-4d8e-b9f4-f28285bd5c8a.json
{
  "opendb_id": "dd1d5777-5e9a-4d8e-b9f4-f28285bd5c8a",
  "metadata": {
    "name": "Western Digital Red Plus 8TB 3.5\" HDD 5640RPM SATA 6.0 Gb/s",
    "manufacturer": "Western Digital",
    "part_numbers": [
      "WD80EFZZ"
    ],
    "series": "Red",
    "variant": "8000GB"
  },
  "capacity": 8000,
  "type": "5640 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B09QQX27GM",
    "newegg_sku": "9SIAD6HGZN3256",
    "bestbuy_sku": 6523110,
    "walmart_sku": 836328689
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/0c9c6e4e-2a32-4e2d-849a-2fe55ec42c8a.json
{
  "opendb_id": "0c9c6e4e-2a32-4e2d-849a-2fe55ec42c8a",
  "metadata": {
    "name": "Netac NV3000 250 GB SSD M.2-2280 PCIe 3.0 x4 NVMe",
    "manufacturer": "Netac",
    "part_numbers": [
      "NT01NV3000-250-E4X"
    ],
    "series": "NV3000",
    "variant": "250GB"
  },
  "capacity": 250,
  "type": "SSD",
  "form_factor": "M.2-2280",
  "interface": "M.2 PCIe 3.0 X4",
  "nvme": true,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/658c79c0-224e-4931-b3fc-d98b6ab7c251.json
{
  "opendb_id": "658c79c0-224e-4931-b3fc-d98b6ab7c251",
  "metadata": {
    "name": "Samsung Spinpoint F3 1TB Internal HDD 7200RPM 3.5\" SATA 3.0 Gb/s",
    "manufacturer": "Samsung",
    "part_numbers": [
      "HD103SJ"
    ],
    "series": "Spinpoint",
    "variant": "1000GB"
  },
  "capacity": 1000,
  "type": "7200 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 3.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B002NXPARA"
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/200b98ee-7d92-48ec-a1bd-1b952f94020b.json
{
  "opendb_id": "200b98ee-7d92-48ec-a1bd-1b952f94020b",
  "metadata": {
    "name": "Seagate BarraCuda 500GB 3.5\" HDD 7200RPM SATA",
    "manufacturer": "Seagate",
    "part_numbers": [
      "ST3500320AS"
    ],
    "series": "BarraCuda",
    "variant": "500GB"
  },
  "capacity": 500,
  "type": "7200 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 3.0 Gb/s",
  "nvme": false,
  "general_product_information": {}
}

=== sebastianp21/PCbuilder/open-db/Storage/9899ea60-8265-4d3a-99f7-e4667361ef05.json
{
  "opendb_id": "9899ea60-8265-4d3a-99f7-e4667361ef05",
  "metadata": {
    "name": "Seagate IronWolf Pro NAS 4TB HDD 3.5\" 7200RPM SATA",
    "manufacturer": "Seagate",
    "part_numbers": [
      "ST4000NT001"
    ],
    "series": "IronWolf",
    "variant": "4000GB"
  },
  "capacity": 4000,
  "type": "7200 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B0B94MX35D",
    "newegg_sku": "N82E16822185079",
    "walmart_sku": 1710439437
  }
}

=== sebastianp21/PCbuilder/open-db/Storage/4ef34900-c043-42e6-8c11-28b8493a771c.json
{
  "opendb_id": "4ef34900-c043-42e6-8c11-28b8493a771c",
  "metadata": {
    "name": "Seagate IronWolf Pro 4TB HDD 3.5\" 7200RPM SATA 6.0 Gb/s",
    "manufacturer": "Seagate",
    "part_numbers": [
      "ST4000NE001"
    ],
    "series": "IronWolf",
    "variant": "4000GB"
  },
  "capacity": 4000,
  "type": "7200 RPM",
  "form_factor": "3.5\"",
  "interface": "SATA 6.0 Gb/s",
  "nvme": false,
  "general_product_information": {
    "amazon_sku": "B07SY4T6F5",
    "newegg_sku": "N82E16822184797",
    "walmart_sku": 443913713
  }
}
